### ISSUE TITLE
error: 'class TM1637' has no member named 'displayStr'

### ISSUE THREAD

**Issue by petermisovic** [Seeed-Studio/Grove_4Digital_Display#16]
Library 1.0.0 installed via Arduino 1.18.13 manager (Ubuntu linux).

tm1637 class defined with pins, initialized in setup {tm1637.init();   tm1637.set(BRIGHT_TYPICAL);   tm1637.clearDisplay();} and called loop{tm1637.displayStr("L0");}

Verify (or upload code) exits with error:
error: 'class TM1637' has no member named 'displayStr'
  tm1637.displayStr("L0");

**Comment by petermisovic** [comment]
It is clear, that library version installed via Arduino 1.18.13, does not contain those member classes in TM1637.h:
![Screenshot from 2021-03-13 23-32-51](https://user-images.githubusercontent.com/11147552/111051599-8f3a1600-8454-11eb-9593-e0c23850fd9e.png).

I have downloaded latest version and building works fine.

**Comment by ackPeng** [comment]
@petermisovic @JoseCintra Is your problem solved now?

**Comment by Lesords** [comment]
Hello,

I\'m going to close this issue, feel free to re-open it if you have any other questions.

[Autocommentary]

**Comment by anzbert** [comment]
@Lesords 
Could this issue please be revisited?

The Arduino IDE still doesnt download the latest version that includes methods like displayStr() for me. I have to manually download the ZIP of the most recent master and add it to my Documents/Arduino/libraries folder.

Maybe you have to create a new release in the repository?!

Thanks a lot!

**Comment by Lesords** [comment]
> @Lesords Could this issue please be revisited?
> 
> The Arduino IDE still doesnt download the latest version that includes methods like displayStr() for me. I have to manually download the ZIP of the most recent master and add it to my Documents/Arduino/libraries folder.
> 
> Maybe you have to create a new release in the repository?!
> 
> Thanks a lot!

Thanks for pointing this out, I've already published the latest release.

It may take a while for this to take effect in the Arduino library manager.

**Comment by anzbert** [comment]
Thx for doing this so quickly 😊 !!
I'll check back in a while to see if it shows up in the arduino IDE
